Revert "Bug 516349 - [Mac] Cannot Restart on Java 9-ea builds (NoClassDefFoundError: javax/annotation/PostConstruct)"
This reverts commit ad13b29e1e8388dda5021e3c10824aa5c44d2e2a.

Change-Id: I88de81b238b000bf4b6db7dfe12e67693fb53f4b