Calling newInstance on Constructor can throw InvocationTargetException
Some versions of Java will throw INvcationTargetExceptoin from
the newInstance call on Constructor instead of the original
NoClassDefFoundError we expect in the test. This change allows
for that by checking the exception cause for NoClassDefFoundError.