Bug 547265 - Fine-grained merging properties in launcher's Main
Merging configuration and extension properties with system properties
in mergeProperties uses System's getProperties and
requires ("java.util.PropertyPermission" "*" "read,write") permission
even if we are not actually going to modify any of these.

Instead, use more fine-grained approach and set individual properties
explicitly with System's setProperty. If/when AccessControlException
occurs, it would provide more specific error message like:

    java.security.AccessControlException: access denied ("java.util.PropertyPermission" "eclipse.exitcode" "write")

Also rename mergeProperties to mergeWithSystemProperties.

Change-Id: I46bb6d539c58cc3dcff3a70dc2dc8544fc0ea7db
Signed-off-by: Mykola Nikishov <mn@mn.com.ua>