Fix warning that fails the build with Tycho 2.1.0.
It uses jdt.core 3.23.0 which gives the false positive warning:
Compiling 48 source files to
/home/jenkins/agent/workspace/rt.equinox.bundles-Gerrit/bundles/org.eclipse.equinox.preferences/target/classes
[WARNING]
/home/jenkins/agent/workspace/rt.equinox.bundles-Gerrit/bundles/org.eclipse.equinox.preferences/src/org/eclipse/core/internal/preferences/SortedProperties.java:[18]
	import java.util.Map.Entry;
	       ^^^^^^^^^^^^^^^^^^^
The import java.util.Map.Entry is never used
1 problem (1 warning)
error: warnings found and -failOnWarning specified

Not reporting ecj bug as 4.18 stream version no longer shows the issue
so it seems fixed.

Change-Id: Idc38378e56f45e88e6eec20985c07c84d96c84c5
Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>