Bug 517507: Remove Java 9 hacks that were added to the launcher in Oxygen M7
Revert "Bug 493761: Platform won't launch on Java 9-ea builds
(InjectionException: NoClassDefFoundError:
javax/annotation/PostConstruct)"

This reverts commit 4295e27d8e41283eadba7aa2e098126b22c5a7a9.

This reverts commit 28ff351cfc1b33eb84c70b295e8a86bf8b70d21f.

This reverts commit 2e0869c0e8cf5f4125a3237f22ed6f166a065fbb.