Bug 493761: Platform won't launch on Java 9-ea builds (InjectionException: NoClassDefFoundError: javax/annotation/PostConstruct)
--permit-illegal-access VM argument is needed to run eclipse with Java 9
but Java 8 does not recognize this argument and fails to start up.

This patch prevents passing the --permit-illegal-access argument to the
JVM if it is present in the VM argument list and the JVM version is < 9.

Change-Id: Id39176a1e4f092d59063111667dd738a0b951ad4
Signed-off-by: Arun Thondapu <arunkumar.thondapu@in.ibm.com>